### ISSUE TITLE
add economy support

### ISSUE THREAD

**Issue by attrib** [attrib/RepairRecipe#7]
Using Vault.

Add economy support.

> Those fully configurable repair costs (with multipliers, based on enchant level AND number of enchants) + economy cost through Vault. Economy cost should be either OR or AND.

**Comment by attrib** [comment]
**Idea #1**
Add for each used base_item the costs. Maybe add API that other Plugins can modify this. The ingot amount needed \* the price set per ingot is the price the user pays to repair.

```
iron_ingot:
    economy_cost: 100 # cost per ingot

enchantment_multiplier_economy: 100 # each level of enchant costs this extra, also per enchantment
enchantment_multiplier_economy_groups: {} # change multiplier per group

economy_costs_extra: true # costs are additionally; if false its base_item or economy
                                                  # this should also be able to set per item
```

**Idea #2**
Set cost per item and decide per item if it is a additional fee or not

```
iron_axe:
    base_item: iron_ingot
    base_amount: 3
    economy_additional_fee: 100 # additional fee to repair from 0 to 100%
```

Only repairable with money:

```
iron_axe:
    economy_cost: 500 # cost to repair item from 0 to 100%
```

Repairable with money or base item:

```
iron_axe:
    base_item: iron_ingot
    base_amount: 3
    economy_cost: 500
```

Enchantment costs per level are set for each enchantment.

**Both**

```
discount_economy: 10 # discount for economy
discount_economy_groups:
    Sponsor: 100
```
