### ISSUE TITLE
configurable base item

### ISSUE THREAD

**Issue by attrib** [attrib/RepairRecipe#8]
make base item and amount configurable -> configurable repair cost

**Comment by attrib** [comment]
Idea by Maresi

> Use the following to set indiviual item values.  If item is not listed, defaults will be used.
> Example: (can use item names or item IDs)

```
diamond_helmet:
    base_item: diamond
      base_ammount: 5
      keep_enchants_chance: 100
      allow_over_repair: true
      enchant_multiplier: 100
      discount: false
      use_highest_enchant: false
```
